# Prometheus Configuration
# Defines scraping targets and alerting rules for system monitoring

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dashboard-backend'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert_rules.yml"